spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: student
        uri: lb://student
        predicates:
        - Path=/student/**
        filters:
           - RewritePath=/student/(?<segment>.*), /echoStudentName/$\{segment}
           
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
      instance:
        preferIpAddress: true
        